### ISSUE TITLE
I want to enjoy it

### ISSUE THREAD

**Issue by getsadzeg** [lapptech/andromeda-management#2]
როგორ შემიძლია გავტესტო?

**Comment by ShavidzeT** [comment]
დაკლონე და apache-ზე ან სხვა ვებ სერვერზე გაუშვი, რომელიც PHP-ზე მუშაობს (გაითვალისწინე ჯერ-ჯერობით შეჩერდა მუშაობა ამ რეპოზე ცოტახნით)

**Comment by getsadzeg** [comment]
OK
